POST http://localhost:3000/api/mobile_passwordReset/locataire
Content-Type: application/json

{
    "email" : "dou@esi.dz"
}

###
PATCH http://localhost:3000/api/mobile_passwordReset/locataire/1/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9sb2NhdGFpcmUiOjEsImlhdCI6MTY0Nzg4MzU5MH0.evASr4mKr7PQFV_pD_jHFD0Q_9PYNLcQ5x0xVfDWkSw
Content-Type: application/json

{
    "password" : "resetreset"
}