POST http://localhost:3000/api/mobile_passwordReset/agent
Content-Type: application/json

{
    "email" : "id_bouloudene@esi.dz"
}

###
PATCH http://localhost:3000/api/mobile_passwordReset/agent/1/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NDc3MzMzODJ9.C6a6Px53oqs32V_o4geTg2btUj34nU_j27iz-sJwRZI
Content-Type: application/json

{
    "password" : "resetreset"
}